name: drive_search_web
version: 0.1.0
author: Dart Team
description: Example of accessing the Google Drive API using Dart in the Browser.
environment:
  sdk: '>=1.6.0 <2.0.0'
dependencies:
  browser: any
  googleapis: ">=0.1.0 <0.2.0"
  http: "0.11.3+9"
  googleapis_auth: ">=0.2.0 <0.3.0"
